### ISSUE TITLE
Latest version as number

### ISSUE THREAD

**Issue by lonix1** [autofac/Documentation#145]
## Problem Statement

Linking to the "latest" version of docs may fail after a while, because the version has changed, and possibly that link may not even exist anymore. So it's best practice to link to a specific version.

So for example, it's better to link to `https://autofac.readthedocs.io/en/v5.2.0/register/registration.html` than to `https://autofac.readthedocs.io/en/latest/register/registration.html`.

The docs site however only has "latest", "stable", "5.2.0", etc.

The latest version is 6.x.x, and we can't link to it.

## Desired Solution

Please add the "latest" version as a number as well, i.e. "6.3.0". If that would get burdensome to update each time, then just "6.x.x" or "6" or "v6" would be fine too.

## Alternatives You've Considered
no

## Additional Context
no

**Comment by tillig** [comment]
We had started tagging really only when we rolled to a new major version because there's sort of a double-edged sword with the tagging:

- Good: You can refer to a specific version of the docs and it won't change out from under you.
- Bad: You follow a link to that specific version and continue navigating around in that version wondering why you can't find the updates you're looking for.

Trying to keep a tag up to date with the latest makes releasing documentation updates harder than it needs to be - it's not just a push or a PR merge, it becomes a need to move the actual git tag along, too. At least, that's how ReadTheDocs works - it's all by git tags.

It's somewhat complicated by the fact that the doc tag matches the core _Autofac_ tag but as we roll versions on the integration libraries, that documentation also changes and there's not actually any solution right now to that doc changing out from under you.

Which isn't to say we won't do something here, I think the point is valid and should be addressed. I'm just not sure what the best route is. Is there an automated way to make a tag follow the head of a particular branch?

**Comment by alistairjevans** [comment]
> Is there an automated way to make a tag follow the head of a particular branch?

Fairly straightforward to do as a Github Action I believe.

**Comment by tillig** [comment]
Oh, good idea. I need to update some of the scripts here to fix npm warnings anyway, I'll see if I can hook that up, too.

**Comment by tillig** [comment]
I added a GitHub Actions workflow to update the tag `v6.0.0` to always align with the `master` branch on push to `master`. This also means the `stable` docs will match up with `v6.0.0` because that's... just how RTD works.

I see the tag is now there, however it does appear ReadTheDocs is having some service issues where no document builds are succeeding right now. As soon as RTD comes back up or we can figure the build issue out, we'll be in business. In the meantime, I'm going to close this as complete since it's as ready to go as it can be.

**Comment by tillig** [comment]
I will note, for folks working on the code, that with the `v6.0.0` tag _moving_, you have to run `git pull --tags --force` a lot on your local checkout or commits/sync operations will fail. It's not a huge deal, just something to be aware of.

Also, it appears the build for docs was failing because we need to pin `docutils` in the RTD build. Sphinx isn't compatible with `docutils` 0.18. I addressed this with the `docs/requirements.txt` file.

**Comment by alistairjevans** [comment]
Noted

**Comment by lonix1** [comment]
Outstanding! And let me take the opportunity to mention that the quality of the Autofac docs overall is one of the highlights of this library in general, many thanks.
