### ISSUE TITLE
docs.autofac.org -> https

### ISSUE THREAD

**Issue by 304NotModified** [autofac/Documentation#68]
I see that in 067be33200c97f205a6edad487809174ae90da77 the url has been changed https://autofac.readthedocs.io/, but that's not needed.

https://docs.autofac.org should also work, because  readthedocs supports (currently) custom domains + https 🎉  See https://docs.readthedocs.io/en/latest/custom_domains.html#custom-domain-ssl and also the working example https://docs.nlog-project.org

As far as I know you need to do the following steps:
- the CNAME needs to be updated to `readthedocs.io.` (currently `autofac.readthedocs.org.`)
- edit and re-save the setting in readthedocs
- SSL should work in one hour

**Comment by alexmg** [comment]
@nblumhardt Can you please check the `CNAME` record when you get a moment?

**Comment by alexmg** [comment]
Thanks for pointing this out @304NotModified. It will be nice to have the docs served on our custom domain again with out the SSL verification issue.

**Comment by nblumhardt** [comment]
Howdy! :-) Just made the change, waiting for DNS to propagate before I can confirm (switched to serving via Cloudflare's CDN/proxy). Will fire it up later today and make sure it's all gone smoothly.

**Comment by nblumhardt** [comment]
![image](https://user-images.githubusercontent.com/342712/52978163-d4c5b980-341b-11e9-9d01-304438e3cf53.png)

**Comment by alexmg** [comment]
Thanks @nblumhardt.

**Comment by 304NotModified** [comment]
maybe turn on SSL by default/enforce ;)

(in read the docs)

![image](https://user-images.githubusercontent.com/5808377/53104351-7f7acc80-352f-11e9-8311-3483f1c2de8d.png)

**Comment by tillig** [comment]
I've updated the setting, but it says it can take up to an hour to get the cert issued. I guess we'll see if I broke it in T-60 minutes. ;)

**Comment by tillig** [comment]
Unclear if perhaps the DNS hasn't propagated or something. The HTTPS status is currently at `pending_verification` and [per this issue](https://github.com/rtfd/readthedocs.org/issues/4736) it appears that could be due to an incorrect CNAME setting to make this work. The example they show is to `dig` your custom domain and the CNAME should return `readthedocs.io`:

```
$ dig docs.unglue.io CNAME +short
readthedocs.io.
```

I just tried this but I see no response for docs.autofac.org. For that unglue.io example, `dig docs.unglue.io CNAME` (without the short response) shows:

```
;; QUESTION SECTION:
;docs.unglue.io.                        IN      CNAME

;; ANSWER SECTION:
docs.unglue.io.         86391   IN      CNAME   readthedocs.io.
```

The same query on docs.autofac.org shows no `ANSWER SECTION` and instead simply an authority section:

```
;; QUESTION SECTION:
;docs.autofac.org.              IN      CNAME

;; AUTHORITY SECTION:
autofac.org.            3524    IN      SOA     eva.ns.cloudflare.com. dns.cloudflare.com. 2030219318 10000 2400 604800 3600
```

I'm not a DNS guy by any means, but I gather that's not what the [RTD system wants](https://docs.readthedocs.io/en/latest/custom_domains.html#custom-domain-ssl). I do see that the docs have this:

> Due to a limitation, a domain cannot be proxied on Cloudflare to another Cloudflare account that also proxies. This results in a “CNAME Cross-User Banned” error. In order to do SSL termination, we must proxy this connection. If you don’t want us to do SSL termination for your domain – which means you are responsible for the SSL certificate – then set your CNAME to `cloudflare-to-cloudflare.readthedocs.io` instead of `readthedocs.io`.

I raise that because I see the Cloudflare reference in the DNS section and I don't know how it's all wired up.

Point being... I'm not sure everything's quite right for the HTTPS bit to work at the moment and there's nothing I can personally do about it.

**Comment by nblumhardt** [comment]
I've just switched on "always use HTTPS" in Cloudflare, should propagate soon.

**Comment by 304NotModified** [comment]
works for me :)

![image](https://user-images.githubusercontent.com/5808377/53129925-2cbe0680-3569-11e9-9786-98db91589a32.png)
