### ISSUE TITLE
Add Preparing event documentation

### ISSUE THREAD

**Issue by tillig** [autofac/Documentation#69]
The [lifetime event docs](https://autofac.readthedocs.io/en/latest/lifetime/events.html) have OnActivating, OnActivated but not [OnPreparing](https://github.com/autofac/Autofac/blob/6dde84e5b0a3f82136a0567a84da498b04e1fa2d/src/Autofac/Core/IComponentRegistration.cs#L83).

**Comment by alistairjevans** [comment]
Taking a brief look at this, it looks like the comments on [OnPreparing](https://github.com/autofac/Autofac/blob/6dde84e5b0a3f82136a0567a84da498b04e1fa2d/src/Autofac/Core/IComponentRegistration.cs#L83) you linked to may not be correct, because there is no Instance property on the [PreparingEventArgs](https://github.com/autofac/Autofac/blob/6dde84e5b0a3f82136a0567a84da498b04e1fa2d/src/Autofac/Core/PreparingEventArgs.cs) class.

If I'm drafting some docs for OnPreparing shall I raise and fix an issue on Autofac to update the comment?

**Comment by tillig** [comment]
Yup, that works.
